### ISSUE TITLE
Needs a better, more in-depth README

### ISSUE THREAD

**Issue by sreekaransrinath** [sreekaransrinath/file_organizer#55]

**Comment by devaslooper** [comment]
@sreekaransrinath  Can I contribute?

**Comment by sreekaransrinath** [comment]
Feel free @devaslooper , I'm assigning you to this task!

**Comment by logan-mo** [comment]
@sreekaransrinath 
Can I contribute as well? I am a new developer, but I have some background in Content writing. I would definitely want to help out.

**Comment by logan-mo** [comment]
I've pushed a description with just rephrasing what was there already in the description. Give it a look.

**Comment by devaslooper** [comment]
@sreekaransrinath I have almost finished the readme. But have been experiencing issues with one of the hyperlinks in the table of contents. Please have a look #63 PR.
It is rendering correctly in my markdown editor but is broken when I pushed to the remote on github

**Comment by lee00286** [comment]
@devaslooper Hello, I have been hovering through the GitHub and found your comment. I think the hyperlink is broken due to the colon(:). How about removing the colons in each bracket, like `[Overview](#Overview)`?

**Comment by devaslooper** [comment]
@lee00286 Thanks for your suggestion. I tried it out, but still no luck..
What is weird to me, is that this is happening only for the 3rd link and not the others 🤔

**Comment by lee00286** [comment]
@devaslooper The hyperlink wouldn't work with blank space between the words. For example, `[What is an Apple](#What-is-an-Apple)` will work fine, while `[What is an Apple](#What is an Apple)` won't work. I would recommend referring some examples in https://github.com/ekalinin/github-markdown-toc.

**Comment by devaslooper** [comment]
@lee00286 The spaces in between was causing the error, along with the fact that markdown doesn't like the text in the () to be in uppercase.
Thanks for your help and the resource! :)

**Comment by vardaan-raj** [comment]
Hello! I have experience in content writing and would like to contribute.
So can you tell me a bit about this and what is it that you specifically want
